apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: demosqlinstance
  namespace: default
spec:
  clusterServiceClassExternalName: azure-sql-12-0
  clusterServicePlanExternalName: standard
  parameters:
    location: <YOURLOCATION>
    resourceGroup: <YOUR_RESOURCE_GROUP>
    firewallRules:
    - startIPAddress: "0.0.0.0"
      endIPAddress: "255.255.255.255"
      name: "AllowAll"
    dtus: 10
