apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-kv
spec:
  containers:
  - name: nginx-flex-kv
    image: nginx
    volumeMounts:
    - name: keyvault
      mountPath: /mysecrets
      readOnly: true
  volumes:
  - name: keyvault
    flexVolume:
      driver: "azure/kv"
      secretRef:
        name: kvcreds
      options:
        keyvaultname: "KEYVAULT_NAME"
        keyvaultobjectnames: "name1;name2;name3"
        keyvaultobjecttypes: "type1,type2,type3"
        resourcegroup: "RESOURCE_GROUP"
        subscriptionid: "SUB_ID"
        tenantid: "TENANT_ID"